export const CHALLENGE_AREA = '[data-test^="challenge "]';
export const COMPLETEREVERSETRANSLATION_TEXTBOX = 'label[dir][lang]';
export const SUBMISSION_BUTTON_LESSON = '[data-test="player-next"]';
export const SUBMISSION_BUTTON_SPAN = 'span';
export const MULTIPLE_CHOICE_CHOICES = '[data-test="challenge-choice"]';
export const IGNORED_CHARACTERS = /[_\-\s,.?!;]/g;
export const LISTENCOMPLETE_TEXTBOX = 'label[dir]';
export const LISTENCOMPLETE_BLANK = '[data-test="challenge-text-input"]';
export const LISTENMATCH_SOUNDWAVE = 'span[style^="--animated-speaker-icon-color"]';
export const MATCH = '[data-test="challenge challenge-match"]';
export const MATCH_BUTTONS = '[class="_3VyQa"]';
export const MATCH_BUTTON_TEXT = '[data-test="challenge-tap-token-text"]';
export const MATCH_BUTTON_SELECTED = 'button[class*="_3Nuad"]';
export const MATCH_BUTTON_NUMBER = 'span[class^="_3"]';
export const NAME_BUTTON = '[data-test="challenge-choice"]';
export const NAME_BUTTON_TEXT = '[data-test="challenge-judge-text"]';
export const NAME_BUTTON_SELECTED = '_3C_oC disCS _2bJln _2-OmZ';
export const NAME_TEXTBOX = '[data-test="challenge-text-input"]';
export const PARTIALREVERSETRANSLATE_TEXTBOX = 'label[dir][lang]';
export const PARTIALREVERSETRANSLATE_TEXT = 'span:not([class]), [contenteditable="true"]';
export const SPEAK_ANSWER_AREA = 'div[dir]';
export const TAPCLOZE_SELECTED = '[class="_1LQx7"]';
export const TAPCLOZE_BUTTON_TEXT = '[data-test="challenge-tap-token-text"]';
export const TAPCOMPLETE_ANSWER_AREA = 'div[dir]';
export const TAPCOMPLETE_SELECTED = 'span[class="_3BS5Z"]';
export const TAPCOMPLETETABLE_CHOICES = '[class="_2Z2xv"]';
export const TAPCOMPLETETABLE_CHOICE_TEXT = '[data-test="challenge-tap-token-text"]';
export const TRANSLATE_TEXTBOX = '[data-test="challenge-translate-input"]';
export const TYPECLOZE_BLANK = '[class="_3bKcr"]';
export const TYPECLOZE_CORRECT = '[class="caPDQ"]';
export const TYPECLOZE_SUBMISSION = '[class="Y5JxA _17nEt"]';
export const TYPECOMPLETETABLE_BLANKS = '[class="_1Rf3h"]';
export const TYPECOMPLETETABLE_ANSWER = '[class="caPDQ"]';
export const TYPECOMPLETETABLE_SUBMISSION = '[class="Y5JxA _17nEt"]';
